### ISSUE TITLE
use ESM import cause Type Error

### ISSUE THREAD

**Issue by Cydiater** [remcohaszing/remark-mermaidjs#4] opened 2022-01-31 07:01 UTC
I'm trying to build a blog with NextJS to support markdown with mermaid syntax. However, it seems that if this package is imported using ESM import instead of CommonJS require, the building is failed due to the following type error

```bash
yarn run v1.22.17
$ next build
Failed to compile.

./lib/posts.ts:47:7
Type error: No overload matches this call.
  Overload 1 of 3, '(plugin: Plugin<[], Node<Data>, Node<Data>>, ...settings: [boolean] | []): Processor<Root, Node<Data>, Node<Data>, string>', gave the following error.
    Argument of type 'Attacher<[(RemarkMermaidOptions | undefined)?], Settings>' is not assignable to parameter of type 'Plugin<[], Node<Data>, Node<Data>>'.
      The 'this' types of each signature are incompatible.
        Type 'Processor<void, Node<Data>, void, void>' is not assignable to type 'Processor<Settings>'.
          Types of property 'use' are incompatible.
            Type '{ <PluginParameters extends any[] = any[], Input = Node<Data>, Output = Input>(plugin: Plugin<PluginParameters, Input, Output>, ...settings: [boolean] | PluginParameters): UsePlugin<...>; <PluginParameters extends any[] = any[], Input = Node<...>, Output = Input>(tuple: [...] | [...]): UsePlugin<...>; (presetOrList:...' is not assignable to type '{ <S extends any[] = [(Settings | undefined)?]>(plugin: Plugin<S, Settings>, ...settings: S): Processor<Settings>; <S extends any[] = [(Settings | undefined)?]>(preset: Preset<...>): Processor<...>; <S extends any[] = [...?]>(pluginTuple: [...]): Processor<...>; (list: PluggableList<...>): Processor<...>; (processor...'.
              Types of parameters 'plugin' and 'plugin' are incompatible.
                The 'this' types of each signature are incompatible.
                  Type 'Processor<void, void, void, void> | Processor<void, any, void, void> | Processor<void, any, any, any> | Processor<any, any, void, void>' is not assignable to type 'Processor<Settings>'.
                    Type 'Processor<void, void, void, void>' is not assignable to type 'Processor<Settings>'.
                      Types of property 'use' are incompatible.
                        Types of parameters 'plugin' and 'plugin' are incompatible.
                          Type 'void | Transformer' is not assignable to type 'void | Transformer<any, any>'.
                            Type 'Transformer' is not assignable to type 'void | Transformer<any, any>'.
                              Type 'Transformer' is not assignable to type 'Transformer<any, any>'.
                                Types of parameters 'file' and 'file' are incompatible.
                                  Property 'contents' is missing in type 'import("/Users/cydiater/Repo/web/node_modules/unified/node_modules/vfile/lib/index").VFile' but required in type 'import("/Users/cydiater/Repo/web/node_modules/vfile/types/index").VFile'.
  Overload 2 of 3, '(tuple: [Plugin<any[], Root, Root>, ...any[]] | [Plugin<any[], Root, Root>, boolean]): Processor<Root, Root, Root, string>', gave the following error.
    Argument of type 'Attacher<[(RemarkMermaidOptions | undefined)?], Settings>' is not assignable to parameter of type '[Plugin<any[], Root, Root>, ...any[]] | [Plugin<any[], Root, Root>, boolean]'.
      Type 'Attacher<[(RemarkMermaidOptions | undefined)?], Settings>' is not assignable to type '[Plugin<any[], Root, Root>, boolean]'.
  Overload 3 of 3, '(presetOrList: Preset | PluggableList): Processor<Root, Root, Root, string>', gave the following error.
    Argument of type 'Attacher<[(RemarkMermaidOptions | undefined)?], Settings>' is not assignable to parameter of type 'Preset | PluggableList'.
      Type 'Attacher<[(RemarkMermaidOptions | undefined)?], Settings>' is missing the following properties from type 'Pluggable<any[]>[]': pop, push, concat, join, and 28 more.

  45 |  // Use remark to convert markdown into HTML string
  46 |  const withMermaid = await remark()
> 47 |  .use(remarkMermaid)
     |       ^
  48 |  .use(html, { sanitize: false })
  49 |  .process(matterResult.content);
  50 |
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Note that if I replace 
```js
import { remarkMermaid } from 'remark-mermaidjs'
```
with 
```js
const { remarkMermaid } = 'remark-mermaidjs'
```
everything works as I expected. I'm not quite sure about what happened, hope you guys could help me.

**Comment by remcohaszing** [comment] 2022-01-31 09:24
THe problem is that the types of unified 9 aren’t fully compatible with the types of unified 10. The reason `const { remarkMermaid } = require('remark-mermaidjs')` (I assume that’s what you meant) works, is that `require()` returns `any`.

I suggest you use

```js
const withMermaid = await remark()
  .use(remarkMermaid as any)
  .use(html, { sanitize: false })
  .process(matterResult.content);
```

or

```js
const withMermaid = await remark()
  // @ts-expect-error https://github.com/remcohaszing/remark-mermaidjs/issues/4
  .use(remarkMermaid)
  .use(html, { sanitize: false })
  .process(matterResult.content);
```

I’m closing this as a duplicate of #1.

---

Also a hint (although I don’t know the context): If you use the pipeline multiple times, I recommend to define it once at the top level and reuse it later. `remark-mermaidjs` reuses the browser instance in this scenario, which significantly improves performance.

**Closed** 2022-01-31 09:27 UTC
