### ISSUE TITLE
When the page is re-rendered, mermaid cannot be rendered successfully.

### ISSUE THREAD

**Issue by lin-mt** [remcohaszing/remark-mermaidjs#13] opened 2022-11-22 16:12 UTC
create with cra. change `App.tsx' to the following code. Launch the application. The page can successfully render mermaid. After clicking the add button, the image rendered by mermaid disappears.

```ts
import React, { useState } from 'react';
import logo from './logo.svg';
import './App.css';
import remarkMermaid from 'remark-mermaidjs'
import ReactMarkdown from 'react-markdown';

const markdown = `
# Hello world!

\`\`\`mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
\`\`\`

\`\`\`js
console.log('hello')
\`\`\`

123
`

function App() {

  const [value, setValue] = useState("123");

  function add() {
    console.log(123);
    setValue("456")
  }

  return (
    <div className="App">
      <button onClick={add}>add</button>
      {value}
      <ReactMarkdown
      className="markdown-body"
      rehypePlugins={[
      ]}
      remarkPlugins={[
        remarkMermaid
      ]}
    >
      {markdown}
    </ReactMarkdown>
    </div>
  );
}

export default App;

```
![iShot_2022-11-23_00 06 55](https://user-images.githubusercontent.com/58337359/203364388-a485d0e9-2beb-4b16-b6f5-5b3cdf6ec226.gif)

**Comment by lin-mt** [comment] 2022-11-22 16:27
and this issue https://github.com/remcohaszing/remark-mermaidjs/issues/12 reproduced

remove `import rehypeRaw from 'rehype-raw';` it can render success!

**Comment by remcohaszing** [comment] 2022-12-03 16:47
I have been able to reproduce the issue. It’s caused by the reuse of the same id in mermaid.

This would be fixed by using a global counter instead of the index to generate the id. I’m open to alternative solutions.

**Closed** 2022-12-05 15:14 UTC
